import type { Metadata } from "next";

import "./globals.css";

import localFont from "next/font/local";

const satoshi = localFont({
  src: [
    {
      path: "../../public/Satoshi-Variable.ttf",
    },
  ],
  variable: "--font-satoshi",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className=""
    >
      <head></head>
      <style>
        {`
          :root {
            --font-satoshi: ${satoshi.variable};
          }

          .font-satoshi {
            font-family: ${satoshi.style.fontFamily.replaceAll("'", "")};
          }
        `}
      </style>
      <body className={`${satoshi.className} min-h-screen text-gray bg-gradient-to-br from-bg-primary to-bg-secondary`}>{children}</body>
    </html>
  );
}
